name: rust_wasm
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  file_picker: ^4.1.5

  image_compression_flutter: ^1.0.2
  palette_generator: ^0.3.2
  js: ^0.6.3

  crypton: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
